# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mydb
  username: postgres
  password: gorgo13
  host: localhost
  port: 5432

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
